d = input('Digite algo:')
print('O tipo primitivo desse valor é ', type(d))
print('Só tem espaços?', d.isspace())
print('É um número?', d.isnumeric())
print('É alfabeto?', d.isalpha())
print('É alfanumérico?', d.isalnum())
print('Esta em letras maiúsculas?', d.isupper())
print('Está em minúsculas?', d.islower())
print('Está capitalizada?', d.istitle())
